package principal.modelos;

public enum TipoAdicional {
	
	COBERTURA_CHOCOLATE,
	COBERTURA_MORANGO,
	COBERTURA_CARAMELO,
	TUBETES_SEM_RECHEIO,
	TUBETES_RECHEADOS,
	FRUTA_MORANGO,
	FRUTA_BANANA,
	FRUTA_CEREJA,
	GANULADO_CHOCOLATE,
	GRANULADO_AMENDOIN;
}
